//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnclePhill.WebAPI_NFeS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFeS
    {
        public long NFeSId { get; set; }
        public long TakerId { get; set; }
        public System.DateTime DateEmission { get; set; }
        public string RPS { get; set; }
        public string DateEmissionRPS { get; set; }
        public string ServicesProvied { get; set; }
        public string LocalService { get; set; }
        public string Note { get; set; }
        public decimal TaxWithheld { get; set; }
        public decimal TotalISS { get; set; }
        public decimal TotalIRRF { get; set; }
        public decimal TotalPIS { get; set; }
        public decimal TotalINSS { get; set; }
        public decimal TotalCONFIS { get; set; }
        public decimal TotalCSLL { get; set; }
        public decimal TotalOther { get; set; }
        public decimal TotalServices { get; set; }
        public decimal ValueDeductions { get; set; }
        public decimal TotalNFeS { get; set; }
    }
}
