//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class tbnfd {
    
    private tbnfdNfd nfdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public tbnfdNfd nfd {
        get {
            return this.nfdField;
        }
        set {
            this.nfdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class tbnfdNfd {
    
    private int numeronfdField;
    
    private int codseriedocumentoField;
    
    private int codnaturezaoperacaoField;
    
    private sbyte codigocidadeField;
    
    private int inscricaomunicipalemissorField;
    
    private string dataemissaoField;
    
    private string razaotomadorField;
    
    private string nomefantasiatomadorField;
    
    private string enderecotomadorField;
    
    private string cidadetomadorField;
    
    private string estadotomadorField;
    
    private string paistomadorField;
    
    private string fonetomadorField;
    
    private string faxtomadorField;
    
    private string ceptomadorField;
    
    private string bairrotomadorField;
    
    private string emailtomadorField;
    
    private string cpfcnpjtomadorField;
    
    private string inscricaoestadualtomadorField;
    
    private string inscricaomunicipaltomadorField;
    
    private string observacaoField;
    
    private tbnfdNfdFatura[] tbfaturaField;
    
    private tbnfdNfdServico[] tbservicoField;
    
    private string razaotransportadoraField;
    
    private string cpfcnpjtransportadoraField;
    
    private string enderecotransportadoraField;
    
    private string tipofreteField;
    
    private string quantidadeField;
    
    private string especieField;
    
    private string pesoliquidoField;
    
    private string pesobrutoField;
    
    private string pisField;
    
    private string cofinsField;
    
    private string csllField;
    
    private string irrfField;
    
    private string inssField;
    
    private string descdeducoesconstrucaoField;
    
    private string totaldeducoesconstrucaoField;
    
    private string tributadonomunicipioField;
    
    private string numerortField;
    
    private string codigoseriertField;
    
    private string dataemissaortField;
    
    private int numerofaturaField;
    
    private bool numerofaturaFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numeronfd {
        get {
            return this.numeronfdField;
        }
        set {
            this.numeronfdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int codseriedocumento {
        get {
            return this.codseriedocumentoField;
        }
        set {
            this.codseriedocumentoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int codnaturezaoperacao {
        get {
            return this.codnaturezaoperacaoField;
        }
        set {
            this.codnaturezaoperacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public sbyte codigocidade {
        get {
            return this.codigocidadeField;
        }
        set {
            this.codigocidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int inscricaomunicipalemissor {
        get {
            return this.inscricaomunicipalemissorField;
        }
        set {
            this.inscricaomunicipalemissorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dataemissao {
        get {
            return this.dataemissaoField;
        }
        set {
            this.dataemissaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string razaotomador {
        get {
            return this.razaotomadorField;
        }
        set {
            this.razaotomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nomefantasiatomador {
        get {
            return this.nomefantasiatomadorField;
        }
        set {
            this.nomefantasiatomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enderecotomador {
        get {
            return this.enderecotomadorField;
        }
        set {
            this.enderecotomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cidadetomador {
        get {
            return this.cidadetomadorField;
        }
        set {
            this.cidadetomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string estadotomador {
        get {
            return this.estadotomadorField;
        }
        set {
            this.estadotomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string paistomador {
        get {
            return this.paistomadorField;
        }
        set {
            this.paistomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fonetomador {
        get {
            return this.fonetomadorField;
        }
        set {
            this.fonetomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string faxtomador {
        get {
            return this.faxtomadorField;
        }
        set {
            this.faxtomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ceptomador {
        get {
            return this.ceptomadorField;
        }
        set {
            this.ceptomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string bairrotomador {
        get {
            return this.bairrotomadorField;
        }
        set {
            this.bairrotomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string emailtomador {
        get {
            return this.emailtomadorField;
        }
        set {
            this.emailtomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cpfcnpjtomador {
        get {
            return this.cpfcnpjtomadorField;
        }
        set {
            this.cpfcnpjtomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string inscricaoestadualtomador {
        get {
            return this.inscricaoestadualtomadorField;
        }
        set {
            this.inscricaoestadualtomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string inscricaomunicipaltomador {
        get {
            return this.inscricaomunicipaltomadorField;
        }
        set {
            this.inscricaomunicipaltomadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string observacao {
        get {
            return this.observacaoField;
        }
        set {
            this.observacaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("fatura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public tbnfdNfdFatura[] tbfatura {
        get {
            return this.tbfaturaField;
        }
        set {
            this.tbfaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("servico", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public tbnfdNfdServico[] tbservico {
        get {
            return this.tbservicoField;
        }
        set {
            this.tbservicoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string razaotransportadora {
        get {
            return this.razaotransportadoraField;
        }
        set {
            this.razaotransportadoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cpfcnpjtransportadora {
        get {
            return this.cpfcnpjtransportadoraField;
        }
        set {
            this.cpfcnpjtransportadoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string enderecotransportadora {
        get {
            return this.enderecotransportadoraField;
        }
        set {
            this.enderecotransportadoraField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tipofrete {
        get {
            return this.tipofreteField;
        }
        set {
            this.tipofreteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string quantidade {
        get {
            return this.quantidadeField;
        }
        set {
            this.quantidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string especie {
        get {
            return this.especieField;
        }
        set {
            this.especieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pesoliquido {
        get {
            return this.pesoliquidoField;
        }
        set {
            this.pesoliquidoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pesobruto {
        get {
            return this.pesobrutoField;
        }
        set {
            this.pesobrutoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string pis {
        get {
            return this.pisField;
        }
        set {
            this.pisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cofins {
        get {
            return this.cofinsField;
        }
        set {
            this.cofinsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string csll {
        get {
            return this.csllField;
        }
        set {
            this.csllField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string irrf {
        get {
            return this.irrfField;
        }
        set {
            this.irrfField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string inss {
        get {
            return this.inssField;
        }
        set {
            this.inssField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string descdeducoesconstrucao {
        get {
            return this.descdeducoesconstrucaoField;
        }
        set {
            this.descdeducoesconstrucaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string totaldeducoesconstrucao {
        get {
            return this.totaldeducoesconstrucaoField;
        }
        set {
            this.totaldeducoesconstrucaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tributadonomunicipio {
        get {
            return this.tributadonomunicipioField;
        }
        set {
            this.tributadonomunicipioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string numerort {
        get {
            return this.numerortField;
        }
        set {
            this.numerortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoseriert {
        get {
            return this.codigoseriertField;
        }
        set {
            this.codigoseriertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string dataemissaort {
        get {
            return this.dataemissaortField;
        }
        set {
            this.dataemissaortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numerofatura {
        get {
            return this.numerofaturaField;
        }
        set {
            this.numerofaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool numerofaturaSpecified {
        get {
            return this.numerofaturaFieldSpecified;
        }
        set {
            this.numerofaturaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class tbnfdNfdFatura {
    
    private int numfaturaField;
    
    private string vencimentofaturaField;
    
    private string valorfaturaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int numfatura {
        get {
            return this.numfaturaField;
        }
        set {
            this.numfaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string vencimentofatura {
        get {
            return this.vencimentofaturaField;
        }
        set {
            this.vencimentofaturaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string valorfatura {
        get {
            return this.valorfaturaField;
        }
        set {
            this.valorfaturaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class tbnfdNfdServico {
    
    private string quantidadeField;
    
    private string descricaoField;
    
    private int codatividadeField;
    
    private string valorunitarioField;
    
    private string aliquotaField;
    
    private string impostoretidoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string quantidade {
        get {
            return this.quantidadeField;
        }
        set {
            this.quantidadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string descricao {
        get {
            return this.descricaoField;
        }
        set {
            this.descricaoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int codatividade {
        get {
            return this.codatividadeField;
        }
        set {
            this.codatividadeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string valorunitario {
        get {
            return this.valorunitarioField;
        }
        set {
            this.valorunitarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string aliquota {
        get {
            return this.aliquotaField;
        }
        set {
            this.aliquotaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string impostoretido {
        get {
            return this.impostoretidoField;
        }
        set {
            this.impostoretidoField = value;
        }
    }
}
